package Models;
// Generated Jul 8, 2015 1:43:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tactividadcomentario generated by hbm2java
 */
@Entity
@Table(name="tactividadcomentario"
    ,catalog="dbappagendajava"
)
public class Tactividadcomentario  implements java.io.Serializable {


     private String codigoActividadComentario;
     private Tactividad tactividad;
     private Tusuarioamigo tusuarioamigo;
     private String comentario;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Tactividadcomentario() {
    }

    public Tactividadcomentario(String codigoActividadComentario, Tactividad tactividad, Tusuarioamigo tusuarioamigo, String comentario, Date fechaRegistro, Date fechaModificacion) {
       this.codigoActividadComentario = codigoActividadComentario;
       this.tactividad = tactividad;
       this.tusuarioamigo = tusuarioamigo;
       this.comentario = comentario;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="codigoActividadComentario", unique=true, nullable=false, length=15)
    public String getCodigoActividadComentario() {
        return this.codigoActividadComentario;
    }
    
    public void setCodigoActividadComentario(String codigoActividadComentario) {
        this.codigoActividadComentario = codigoActividadComentario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoActividad", nullable=false)
    public Tactividad getTactividad() {
        return this.tactividad;
    }
    
    public void setTactividad(Tactividad tactividad) {
        this.tactividad = tactividad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoUsuarioAmigo", nullable=false)
    public Tusuarioamigo getTusuarioamigo() {
        return this.tusuarioamigo;
    }
    
    public void setTusuarioamigo(Tusuarioamigo tusuarioamigo) {
        this.tusuarioamigo = tusuarioamigo;
    }

    
    @Column(name="comentario", nullable=false, length=65535)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaRegistro", nullable=false, length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaModificacion", nullable=false, length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


