package Models;
// Generated Jul 8, 2015 1:43:35 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tunidadmedida generated by hbm2java
 */
@Entity
@Table(name = "tunidadmedida", catalog = "dbappagendajava"
)
public class Tunidadmedida implements java.io.Serializable {

    private String codigoUnidadMedida;
    private String nombre;
    private String descripcion;
    private Date fechaRegistro;
    private Date fechaModificacion;
    private Set tactividadpresupuestos = new HashSet(0);

    public Tunidadmedida() {
    }

    public Tunidadmedida(String codigoUnidadMedida, String nombre, String descripcion, Date fechaRegistro, Date fechaModificacion) {
        this.codigoUnidadMedida = codigoUnidadMedida;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }

    public Tunidadmedida(String codigoUnidadMedida, String nombre, String descripcion, Date fechaRegistro, Date fechaModificacion, Set tactividadpresupuestos) {
        this.codigoUnidadMedida = codigoUnidadMedida;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
        this.tactividadpresupuestos = tactividadpresupuestos;
    }

    @Id

    @Column(name = "codigoUnidadMedida", unique = true, nullable = false, length = 15)
    public String getCodigoUnidadMedida() {
        return this.codigoUnidadMedida;
    }

    public void setCodigoUnidadMedida(String codigoUnidadMedida) {
        this.codigoUnidadMedida = codigoUnidadMedida;
    }

    @Column(name = "nombre", nullable = false, length = 30)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion", nullable = false, length = 65535)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechaRegistro", nullable = false, length = 19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechaModificacion", nullable = false, length = 19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tunidadmedida")
    public Set<Tactividadpresupuesto> getTactividadpresupuestos() {
        return this.tactividadpresupuestos;
    }

    public void setTactividadpresupuestos(Set tactividadpresupuestos) {
        this.tactividadpresupuestos = tactividadpresupuestos;
    }

}
