package Models;
// Generated Jul 8, 2015 1:43:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tusuarioamigotelefono generated by hbm2java
 */
@Entity
@Table(name="tusuarioamigotelefono"
    ,catalog="dbappagendajava"
)
public class Tusuarioamigotelefono  implements java.io.Serializable {


     private String codigoUsuarioAmigoTelefono;
     private Tusuarioamigo tusuarioamigo;
     private String descripcion;
     private String telefono;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Tusuarioamigotelefono() {
    }

    public Tusuarioamigotelefono(String codigoUsuarioAmigoTelefono, Tusuarioamigo tusuarioamigo, String descripcion, String telefono, Date fechaRegistro, Date fechaModificacion) {
       this.codigoUsuarioAmigoTelefono = codigoUsuarioAmigoTelefono;
       this.tusuarioamigo = tusuarioamigo;
       this.descripcion = descripcion;
       this.telefono = telefono;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="codigoUsuarioAmigoTelefono", unique=true, nullable=false, length=15)
    public String getCodigoUsuarioAmigoTelefono() {
        return this.codigoUsuarioAmigoTelefono;
    }
    
    public void setCodigoUsuarioAmigoTelefono(String codigoUsuarioAmigoTelefono) {
        this.codigoUsuarioAmigoTelefono = codigoUsuarioAmigoTelefono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoUsuarioAmigo", nullable=false)
    public Tusuarioamigo getTusuarioamigo() {
        return this.tusuarioamigo;
    }
    
    public void setTusuarioamigo(Tusuarioamigo tusuarioamigo) {
        this.tusuarioamigo = tusuarioamigo;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="telefono", nullable=false, length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaRegistro", nullable=false, length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaModificacion", nullable=false, length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


