package Models;
// Generated Jul 8, 2015 1:43:35 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tusuario generated by hbm2java
 */
@Entity
@Table(name = "tusuario", catalog = "dbappagendajava")
@NamedQueries({@NamedQuery(name = "@HQL_GET_ALL_TUSUARIO", query = "from Tusuario")})
public class Tusuario implements java.io.Serializable {

    @Id
    @Column(name = "codigoUsuario", unique = true, nullable = false, length = 15)
    private String codigoUsuario;

    @Column(name = "nombre", nullable = false, length = 30)
    private String nombre;

    @Column(name = "apellidoPaterno", nullable = false, length = 20)
    private String apellidoPaterno;

    @Column(name = "apellidoMaterno", nullable = false, length = 20)
    private String apellidoMaterno;

    @Column(name = "correoElectronico", nullable = false, length = 30)
    private String correoElectronico;

    @Column(name = "contrasenia", nullable = false, length = 700)
    private String contrasenia;

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaNacimiento", nullable = false, length = 10)
    private Date fechaNacimiento;
    @Column(name = "sexo", nullable = false)
    private boolean sexo;
    @Column(name = "telefono", nullable = false, length = 20)
    private String telefono;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechaRegistro", nullable = false, length = 19)
    private Date fechaRegistro;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechaModificacion", nullable = false, length = 19)
    private Date fechaModificacion;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
    private Set<Tusuarioamigo> tusuarioamigos = new HashSet(0);
   
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
    private Set<Tactividad> tactividads = new HashSet(0);

    public Tusuario() {
    }

    public Tusuario(String codigoUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico, String contrasenia, Date fechaNacimiento, boolean sexo, String telefono, Date fechaRegistro, Date fechaModificacion) {
        this.codigoUsuario = codigoUsuario;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correoElectronico = correoElectronico;
        this.contrasenia = contrasenia;
        this.fechaNacimiento = fechaNacimiento;
        this.sexo = sexo;
        this.telefono = telefono;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }

    public Tusuario(String codigoUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico, String contrasenia, Date fechaNacimiento, boolean sexo, String telefono, Date fechaRegistro, Date fechaModificacion, Set tusuarioamigos, Set tactividads) {
        this.codigoUsuario = codigoUsuario;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correoElectronico = correoElectronico;
        this.contrasenia = contrasenia;
        this.fechaNacimiento = fechaNacimiento;
        this.sexo = sexo;
        this.telefono = telefono;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
        this.tusuarioamigos = tusuarioamigos;
        this.tactividads = tactividads;
    }

    public String getCodigoUsuario() {
        return this.codigoUsuario;
    }

    public void setCodigoUsuario(String codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }

    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }

    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    public String getCorreoElectronico() {
        return this.correoElectronico;
    }

    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    public String getContrasenia() {
        return this.contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public boolean isSexo() {
        return this.sexo;
    }

    public void setSexo(boolean sexo) {
        this.sexo = sexo;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public Set<Tusuarioamigo> getTusuarioamigos() {
        return this.tusuarioamigos;
    }

    public void setTusuarioamigos(Set tusuarioamigos) {
        this.tusuarioamigos = tusuarioamigos;
    }

    public Set<Tactividad> getTactividads() {
        return this.tactividads;
    }

    public void setTactividads(Set tactividads) {
        this.tactividads = tactividads;
    }

}
