package Pojos;
// Generated Jul 7, 2015 2:55:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tactividadparticipante generated by hbm2java
 */
@Entity
@Table(name="tactividadparticipante"
    ,catalog="dbappagendajava"
)
public class Tactividadparticipante  implements java.io.Serializable {


     private String codigoActividadParticipante;
     private Tactividad tactividad;
     private Tusuarioamigo tusuarioamigo;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Tactividadparticipante() {
    }

    public Tactividadparticipante(String codigoActividadParticipante, Tactividad tactividad, Tusuarioamigo tusuarioamigo, Date fechaRegistro, Date fechaModificacion) {
       this.codigoActividadParticipante = codigoActividadParticipante;
       this.tactividad = tactividad;
       this.tusuarioamigo = tusuarioamigo;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="codigoActividadParticipante", unique=true, nullable=false, length=15)
    public String getCodigoActividadParticipante() {
        return this.codigoActividadParticipante;
    }
    
    public void setCodigoActividadParticipante(String codigoActividadParticipante) {
        this.codigoActividadParticipante = codigoActividadParticipante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoActividad", nullable=false)
    public Tactividad getTactividad() {
        return this.tactividad;
    }
    
    public void setTactividad(Tactividad tactividad) {
        this.tactividad = tactividad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoUsuarioAmigo", nullable=false)
    public Tusuarioamigo getTusuarioamigo() {
        return this.tusuarioamigo;
    }
    
    public void setTusuarioamigo(Tusuarioamigo tusuarioamigo) {
        this.tusuarioamigo = tusuarioamigo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaRegistro", nullable=false, length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaModificacion", nullable=false, length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


