package Pojos;
// Generated Jul 7, 2015 2:55:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tactividadpresupuesto generated by hbm2java
 */
@Entity
@Table(name="tactividadpresupuesto"
    ,catalog="dbappagendajava"
)
public class Tactividadpresupuesto  implements java.io.Serializable {


     private String codigoActividadPresupuesto;
     private Tactividad tactividad;
     private Tunidadmedida tunidadmedida;
     private String descripcion;
     private BigDecimal precioUnitario;
     private float cantidad;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Tactividadpresupuesto() {
    }

    public Tactividadpresupuesto(String codigoActividadPresupuesto, Tactividad tactividad, Tunidadmedida tunidadmedida, String descripcion, BigDecimal precioUnitario, float cantidad, Date fechaRegistro, Date fechaModificacion) {
       this.codigoActividadPresupuesto = codigoActividadPresupuesto;
       this.tactividad = tactividad;
       this.tunidadmedida = tunidadmedida;
       this.descripcion = descripcion;
       this.precioUnitario = precioUnitario;
       this.cantidad = cantidad;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="codigoActividadPresupuesto", unique=true, nullable=false, length=15)
    public String getCodigoActividadPresupuesto() {
        return this.codigoActividadPresupuesto;
    }
    
    public void setCodigoActividadPresupuesto(String codigoActividadPresupuesto) {
        this.codigoActividadPresupuesto = codigoActividadPresupuesto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoActividad", nullable=false)
    public Tactividad getTactividad() {
        return this.tactividad;
    }
    
    public void setTactividad(Tactividad tactividad) {
        this.tactividad = tactividad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoUnidadMedida", nullable=false)
    public Tunidadmedida getTunidadmedida() {
        return this.tunidadmedida;
    }
    
    public void setTunidadmedida(Tunidadmedida tunidadmedida) {
        this.tunidadmedida = tunidadmedida;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="precioUnitario", nullable=false, precision=8)
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }

    
    @Column(name="cantidad", nullable=false, precision=12, scale=0)
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaRegistro", nullable=false, length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaModificacion", nullable=false, length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


