package Pojos;
// Generated Jul 7, 2015 5:14:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tactividad generated by hbm2java
 */
public class Tactividad  implements java.io.Serializable {


     private String codigoActividad;
     private Tusuario tusuario;
     private String nombre;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private BigDecimal presupuestoTotal;
     private char estado;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set tactividadpresupuestos = new HashSet(0);
     private Set tactividadparticipantes = new HashSet(0);
     private Set tactividadcomentarios = new HashSet(0);

    public Tactividad() {
    }

	
    public Tactividad(String codigoActividad, Tusuario tusuario, String nombre, String descripcion, Date fechaInicio, Date fechaFin, BigDecimal presupuestoTotal, char estado, Date fechaRegistro, Date fechaModificacion) {
        this.codigoActividad = codigoActividad;
        this.tusuario = tusuario;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.presupuestoTotal = presupuestoTotal;
        this.estado = estado;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Tactividad(String codigoActividad, Tusuario tusuario, String nombre, String descripcion, Date fechaInicio, Date fechaFin, BigDecimal presupuestoTotal, char estado, Date fechaRegistro, Date fechaModificacion, Set tactividadpresupuestos, Set tactividadparticipantes, Set tactividadcomentarios) {
       this.codigoActividad = codigoActividad;
       this.tusuario = tusuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.presupuestoTotal = presupuestoTotal;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.tactividadpresupuestos = tactividadpresupuestos;
       this.tactividadparticipantes = tactividadparticipantes;
       this.tactividadcomentarios = tactividadcomentarios;
    }
   
    public String getCodigoActividad() {
        return this.codigoActividad;
    }
    
    public void setCodigoActividad(String codigoActividad) {
        this.codigoActividad = codigoActividad;
    }
    public Tusuario getTusuario() {
        return this.tusuario;
    }
    
    public void setTusuario(Tusuario tusuario) {
        this.tusuario = tusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public BigDecimal getPresupuestoTotal() {
        return this.presupuestoTotal;
    }
    
    public void setPresupuestoTotal(BigDecimal presupuestoTotal) {
        this.presupuestoTotal = presupuestoTotal;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getTactividadpresupuestos() {
        return this.tactividadpresupuestos;
    }
    
    public void setTactividadpresupuestos(Set tactividadpresupuestos) {
        this.tactividadpresupuestos = tactividadpresupuestos;
    }
    public Set getTactividadparticipantes() {
        return this.tactividadparticipantes;
    }
    
    public void setTactividadparticipantes(Set tactividadparticipantes) {
        this.tactividadparticipantes = tactividadparticipantes;
    }
    public Set getTactividadcomentarios() {
        return this.tactividadcomentarios;
    }
    
    public void setTactividadcomentarios(Set tactividadcomentarios) {
        this.tactividadcomentarios = tactividadcomentarios;
    }




}


