package Pojos;
// Generated Jul 7, 2015 2:55:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tactividad generated by hbm2java
 */
@Entity
@Table(name="tactividad"
    ,catalog="dbappagendajava"
)
public class Tactividad  implements java.io.Serializable {


     private String codigoActividad;
     private Tusuario tusuario;
     private String nombre;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private BigDecimal presupuestoTotal;
     private char estado;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set tactividadpresupuestos = new HashSet(0);
     private Set tactividadparticipantes = new HashSet(0);
     private Set tactividadcomentarios = new HashSet(0);

    public Tactividad() {
    }

	
    public Tactividad(String codigoActividad, Tusuario tusuario, String nombre, String descripcion, Date fechaInicio, Date fechaFin, BigDecimal presupuestoTotal, char estado, Date fechaRegistro, Date fechaModificacion) {
        this.codigoActividad = codigoActividad;
        this.tusuario = tusuario;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.presupuestoTotal = presupuestoTotal;
        this.estado = estado;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Tactividad(String codigoActividad, Tusuario tusuario, String nombre, String descripcion, Date fechaInicio, Date fechaFin, BigDecimal presupuestoTotal, char estado, Date fechaRegistro, Date fechaModificacion, Set tactividadpresupuestos, Set tactividadparticipantes, Set tactividadcomentarios) {
       this.codigoActividad = codigoActividad;
       this.tusuario = tusuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.presupuestoTotal = presupuestoTotal;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.tactividadpresupuestos = tactividadpresupuestos;
       this.tactividadparticipantes = tactividadparticipantes;
       this.tactividadcomentarios = tactividadcomentarios;
    }
   
     @Id 

    
    @Column(name="codigoActividad", unique=true, nullable=false, length=15)
    public String getCodigoActividad() {
        return this.codigoActividad;
    }
    
    public void setCodigoActividad(String codigoActividad) {
        this.codigoActividad = codigoActividad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoUsuario", nullable=false)
    public Tusuario getTusuario() {
        return this.tusuario;
    }
    
    public void setTusuario(Tusuario tusuario) {
        this.tusuario = tusuario;
    }

    
    @Column(name="nombre", nullable=false, length=700)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaInicio", nullable=false, length=19)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaFin", nullable=false, length=19)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="presupuestoTotal", nullable=false, precision=8)
    public BigDecimal getPresupuestoTotal() {
        return this.presupuestoTotal;
    }
    
    public void setPresupuestoTotal(BigDecimal presupuestoTotal) {
        this.presupuestoTotal = presupuestoTotal;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaRegistro", nullable=false, length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaModificacion", nullable=false, length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tactividad")
    public Set getTactividadpresupuestos() {
        return this.tactividadpresupuestos;
    }
    
    public void setTactividadpresupuestos(Set tactividadpresupuestos) {
        this.tactividadpresupuestos = tactividadpresupuestos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tactividad")
    public Set getTactividadparticipantes() {
        return this.tactividadparticipantes;
    }
    
    public void setTactividadparticipantes(Set tactividadparticipantes) {
        this.tactividadparticipantes = tactividadparticipantes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tactividad")
    public Set getTactividadcomentarios() {
        return this.tactividadcomentarios;
    }
    
    public void setTactividadcomentarios(Set tactividadcomentarios) {
        this.tactividadcomentarios = tactividadcomentarios;
    }




}


