package Pojos;
// Generated Jul 7, 2015 5:14:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tusuarioamigotelefono generated by hbm2java
 */
public class Tusuarioamigotelefono  implements java.io.Serializable {


     private String codigoUsuarioAmigoTelefono;
     private Tusuarioamigo tusuarioamigo;
     private String descripcion;
     private String telefono;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Tusuarioamigotelefono() {
    }

    public Tusuarioamigotelefono(String codigoUsuarioAmigoTelefono, Tusuarioamigo tusuarioamigo, String descripcion, String telefono, Date fechaRegistro, Date fechaModificacion) {
       this.codigoUsuarioAmigoTelefono = codigoUsuarioAmigoTelefono;
       this.tusuarioamigo = tusuarioamigo;
       this.descripcion = descripcion;
       this.telefono = telefono;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public String getCodigoUsuarioAmigoTelefono() {
        return this.codigoUsuarioAmigoTelefono;
    }
    
    public void setCodigoUsuarioAmigoTelefono(String codigoUsuarioAmigoTelefono) {
        this.codigoUsuarioAmigoTelefono = codigoUsuarioAmigoTelefono;
    }
    public Tusuarioamigo getTusuarioamigo() {
        return this.tusuarioamigo;
    }
    
    public void setTusuarioamigo(Tusuarioamigo tusuarioamigo) {
        this.tusuarioamigo = tusuarioamigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


